server:
  port: 20003
spring:
  application:
    name: productService
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/pms?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址

mybatis:
  configuration-properties:
    offsetAsPageNum: true
    rowBoundsWithCount: true
    reasonable: true
    log.level: debug




imageSave:
  path: C:/productImage/
  id: 1
  showPath: http://127.0.0.1:8888/productService/productImage/
